### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by mjseid** [cloudfoundry-incubator/datadog-firehose-nozzle-release#3]
Hello, 
   there doesn't seem to be any documentation for how to deploy this release in the README.  Is it located somewhere I'm not seeing?

Also any chance you can post a stub.yml for vsphere?  Thanks

**Comment by Jim-Campbell** [comment]
Does this help?

Deploying a Nozzle to the Loggregator Firehose
https://docs.cloudfoundry.org/loggregator/nozzle-tutorial.html

On Wed, Apr 6, 2016 at 10:26 PM, Mark Seidenstricker <
notifications@github.com> wrote:

> Hello,
> there doesn't seem to be any documentation for how to deploy this release
> in the README. Is it located somewhere I'm not seeing?
> 
> Also any chance you can post a stub.yml for vsphere? Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle-release/issues/3

## 

Jim Campbell | Product Manager | Cloud Foundry | Pivotal.io | 303.618.0963

**Comment by mjseid** [comment]
Ah, yeah that would do it.  I've got it working on vsphere with some suggestions from the other issue.  

Might be good enough just to put that link in the Readme in case others can't find it either.  Either way, thank you for pointing it out.

**Comment by Jim-Campbell** [comment]
Done. thanks for the pointer.
